### ISSUE TITLE
Large datasets

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/HBN-wearable-analysis#1]
These datasets are large, which makes plotting them interactively problematic. Additionally, I don't know how to live host from [Open Science Framework](https://osf.io/dg869/).

**Comment by binarybottle** [comment]
I usually store static images on OSF and link to them from a website.  It's okay if our first analysis is non-interactive.

**Comment by shnizzedy** [comment]
fa1115c4b48691ec8253a6faf83dbe28e1b0e575
